

# Permalinks
permalink:        pretty

# Setup
title:            Jono & Film
tagline:          'Jono does Film'
description:      'Jono does Film'
url:              http://foopod.github.io/photos
baseurl:          /

author:
  name:           'Jono Shields'
  url:            https://twitter.com/matapihi

paginate:         10

gems:
  - jekyll-paginate
  - jekyll-gist
  
# Custom
instagram : jono_learns_film
